#!/usr/bin/env bash

readonly TMP_FILE=/tmp/arradio

: ${INSTALL_DIR:=/usr/local/bin}
: ${ARRADIO_HOME:=$HOME/.arradio}

msgError() {
  echo "ERROR: $@" 2>&1
  exit 1
}

# Check for dependencies
for dep in xmllint curl; do
  which $dep >/dev/null 2>&1
  [[ $? -ne 0 ]] && msgError "dependency not found '$dep'"
done

# Check for player application
: ${found:=0}
for player in mpv mplayer vlc; do
  which $player >/dev/null 2>&1
  [[ $? -eq 0 ]] && found=1
done
[[ $found -eq 0 ]] && msgError "player application not found. mpv, mplayer or vlc is required"

# Create HOME's stuff
mkdir -p $ARRADIO_HOME/favorites

# Download a copy
curl -fsSL https://raw.githubusercontent.com/sepen/arradio/master/arradio -o $TMP_FILE

# Check installation directory exists and permissions is granted
: ${sudo_cmd:=sudo}
[[ -w $INSTALL_DIR ]] && sudo_cmd=

# Install (with sudo if required)
$sudo_cmd install -m 0755 $TMP_FILE $INSTALL_DIR/arradio

rm -f $TMP_FILE

# End of file
