#!/usr/bin/env bash

ui_theme_name="basic"
ui_theme_description="Basic arradio UI theme designed for portability"
ui_theme_palette="8-bit"

# Main text
fg='fg:247'
# Preview window text
preview_fg='preview-fg:242'
# Background
bg='bg:233'
# Preview window background
preview_bg='preview-bg:232'
# Highlighted substrings
hl='hl:69'
# Text (current line)
fg_plus='fg+:255'
# Background (current line)
bg_plus='bg+:236'
# Gutter on the left
gutter='gutter:233'
# Highlighted substrings (current line)
hl_plus='hl+:215'
# Info line (match counters)
info='info:240'
# Border around the window (--border and --preview)
border='border:238'
# Main scrollbar
scrollbar='scrollbar:240'
# Border around the preview window (--preview)
preview_border='preview-border:238'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:240'
# Horizontal separator on info line
separator='separator:238'
# Border label (--border-label and --preview-label)
label='label:255'
# Border label of the preview window (--preview-label)
preview_label='preview-label:242'
# Prompt
prompt='prompt:69'
# Pointer to the current line
pointer='pointer:208'
# Multi-select marker
marker='marker:208'
# Streaming input indicator
spinner='spinner:69'
# Header
header='header:102'
