#!/usr/bin/env bash

ui_theme_name="chalkboard8"
ui_theme_description="256-color version of the Chalkboard theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:254'
# Preview window text
preview_fg='preview-fg:254'
# Background
bg='bg:16'
# Preview window background
preview_bg='preview-bg:16'
# Highlighted substrings
hl='hl:222'
# Text (current line)
fg_plus='fg+:22'
# Background (current line)
bg_plus='bg+:28'
# Gutter on the left
gutter='gutter:22'
# Highlighted substrings (current line)
hl_plus='hl+:120'
# Info line (match counters)
info='info:222'
# Border around the window (--border and --preview)
border='border:28'
# Main scrollbar
scrollbar='scrollbar:28'
# Border around the preview window (--preview)
preview_border='preview-border:28'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:28'
# Horizontal separator on info line
separator='separator:222'
# Border label (--border-label and --preview-label)
label='label:117'
# Border label of the preview window (--preview-label)
preview_label='preview-label:117'
# Prompt
prompt='prompt:117'
# Pointer to the current line
pointer='pointer:120'
# Multi-select marker
marker='marker:205'
# Streaming input indicator
spinner='spinner:222'
# Header
header='header:222'
