#!/usr/bin/env bash

ui_theme_name="gruvbox8"
ui_theme_description="256-color version of the Gruvbox theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:230'
# Preview window text
preview_fg='preview-fg:230'
# Background
bg='bg:236'
# Preview window background
preview_bg='preview-bg:236'
# Highlighted substrings
hl='hl:245'
# Text (current line)
fg_plus='fg+:230'
# Background (current line)
bg_plus='bg+:238'
# Gutter on the left
gutter='gutter:236'
# Highlighted substrings (current line)
hl_plus='hl+:202'
# Info line (match counters)
info='info:71'
# Border around the window (--border and --preview)
border='border:#808080'
# Main scrollbar
scrollbar='scrollbar:#7E8E91'
# Border around the preview window (--preview)
preview_border='preview-border:#808080'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:#7E8E91'
# Horizontal separator on info line
separator='separator:#808080'
# Border label (--border-label and --preview-label)
label='label:202'
# Border label of the preview window (--preview-label)
preview_label='preview-label:202'
# Prompt
prompt='prompt:202'
# Pointer to the current line
pointer='pointer:#8EC07C'
# Multi-select marker
marker='marker:#8EC07C'
# Streaming input indicator
spinner='spinner:202'
# Header
header='header:145'
