#!/usr/bin/env bash

ui_theme_name="partypop8"
ui_theme_description="256-color version of the PartyPop theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:15'
# Preview window text
preview_fg='preview-fg:220'
# Background
bg='bg:18'
# Preview window background
preview_bg='preview-bg:18'
# Highlighted substrings
hl='hl:201'
# Text (current line)
fg_plus='fg+:51'
# Background (current line)
bg_plus='bg+:236'
# Gutter on the left
gutter='gutter:18'
# Highlighted substrings (current line)
hl_plus='hl+:208'
# Info line (match counters)
info='info:118'
# Border around the window (--border and --preview)
border='border:199'
# Main scrollbar
scrollbar='scrollbar:33'
# Border around the preview window (--preview)
preview_border='preview-border:199'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:33'
# Horizontal separator on info line
separator='separator:214'
# Border label (--border-label and --preview-label)
label='label:190'
# Border label of the preview window (--preview-label)
preview_label='preview-label:226'
# Prompt
prompt='prompt:45'
# Pointer to the current line
pointer='pointer:201'
# Multi-select marker
marker='marker:46'
# Streaming input indicator
spinner='spinner:226'
# Header
header='header:51'
