#!/usr/bin/env bash
ui_theme_name="rasta8"
ui_theme_description="256-color version of the Rasta theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:15'
# Preview window text
preview_fg='preview-fg:250'
# Background
bg='bg:16'
# Preview window background
preview_bg='preview-bg:16'
# Highlighted substrings
hl='hl:220'
# Text (current line)
fg_plus='fg+:15'
# Background (current line)
bg_plus='bg+:233'
# Gutter on the left
gutter='gutter:16'
# Highlighted substrings (current line)
hl_plus='hl+:34'
# Info line (match counters)
info='info:196'
# Border around the window (--border and --preview)
border='border:34'
# Main scrollbar
scrollbar='scrollbar:34'
# Border around the preview window (--preview)
preview_border='preview-border:34'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:34'
# Horizontal separator on info line
separator='separator:220'
# Border label (--border-label and --preview-label)
label='label:196'
# Border label of the preview window (--preview-label)
preview_label='preview-label:220'
# Prompt
prompt='prompt:34'
# Pointer to the current line
pointer='pointer:220'
# Multi-select marker
marker='marker:196'
# Streaming input indicator
spinner='spinner:34'
# Header
header='header:220'
