#!/usr/bin/env bash

ui_theme_name="retroblast8"
ui_theme_description="256-color version of the RetroBlast theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:15'
# Preview window text
preview_fg='preview-fg:15'
# Background
bg='bg:0'
# Preview window background
preview_bg='preview-bg:0'
# Highlighted substrings
hl='hl:51'
# Text (current line)
fg_plus='fg+:226'
# Background (current line)
bg_plus='bg+:233'
# Gutter on the left
gutter='gutter:0'
# Highlighted substrings (current line)
hl_plus='hl+:201'
# Info line (match counters)
info='info:46'
# Border around the window (--border and --preview)
border='border:196'
# Main scrollbar
scrollbar='scrollbar:196'
# Border around the preview window (--preview)
preview_border='preview-border:196'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:196'
# Horizontal separator on info line
separator='separator:51'
# Border label (--border-label and --preview-label)
label='label:226'
# Border label of the preview window (--preview-label)
preview_label='preview-label:201'
# Prompt
prompt='prompt:46'
# Pointer to the current line
pointer='pointer:201'
# Multi-select marker
marker='marker:51'
# Streaming input indicator
