#!/usr/bin/env bash
ui_theme_name="retrowave8"
ui_theme_description="256-color version of the Retrowave theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:117'
# Preview window text
preview_fg='preview-fg:123'
# Background
bg='bg:17'
# Preview window background
preview_bg='preview-bg:17'
# Highlighted substrings
hl='hl:199'
# Text (current line)
fg_plus='fg+:115'
# Background (current line)
bg_plus='bg+:18'
# Gutter on the left
gutter='gutter:17'
# Highlighted substrings (current line)
hl_plus='hl+:199'
# Info line (match counters)
info='info:220'
# Border around the window (--border and --preview)
border='border:25'
# Main scrollbar
scrollbar='scrollbar:25'
# Border around the preview window (--preview)
preview_border='preview-border:25'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:25'
# Horizontal separator on info line
separator='separator:220'
# Border label (--border-label and --preview-label)
label='label:199'
# Border label of the preview window (--preview-label)
preview_label='preview-label:199'
# Prompt
prompt='prompt:199'
# Pointer to the current line
pointer='pointer:123'
# Multi-select marker
marker='marker:199'
# Streaming input indicator
spinner='spinner:214'
# Header
header='header:220'
