#!/usr/bin/env bash

ui_theme_name="seoul8"
ui_theme_description="256-color version of the Seoul theme"
ui_theme_palette="8-bit"

# Main text
fg='fg:235'
# Preview window text
preview_fg='preview-fg:232'
# Background
bg='bg:254'
# Preview window background
preview_bg='preview-bg:254'
# Highlighted substrings
hl='hl:65'
# Text (current line)
fg_plus='fg+:235'
# Background (current line)
bg_plus='bg+:253'
# Gutter on the left
gutter='gutter:254'
# Highlighted substrings (current line)
hl_plus='hl+:110'
# Info line (match counters)
info='info:143'
# Border around the window (--border and --preview)
border='border:240'
# Main scrollbar
scrollbar='scrollbar:240'
# Border around the preview window (--preview)
preview_border='preview-border:240'
# Preview scrollbar
preview_scrollbar='preview-scrollbar:240'
# Horizontal separator on info line
separator='separator:240'
# Border label (--border-label and --preview-label)
label='label:110'
# Border label of the preview window (--preview-label)
preview_label='preview-label:110'
# Prompt
prompt='prompt:110'
# Pointer to the current line
pointer='pointer:161'
# Multi-select marker
marker='marker:168'
# Streaming input indicator
spinner='spinner:108'
# Header
header='header:65'
